name: Build and Release

# on: workflow_dispatch
on:
  push:
    tags:
       - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Build App
        run: pnpm build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.ANT_CHAT_RELEASE }}
          body_path: ./CHANGELOG.md

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_KEY }}
          source: ./dist
          target: /var/www/ant-chat

      - name: Restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_KEY }}
          script: nginx -s reload
